# 基本は github.com のレポジトリーを指定するだけ
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'haya14busa/vim-easymotion'

[[plugins]]
repo = 'kana/vim-smartinput'

# NeoBundle 'osyo-manga/vim-over'
# NeoBundle 'terryma/vim-multiple-cursors'
# NeoBundle 'Yggdroot/indentLine'
# NeoBundle 'maksimr/vim-jsbeautify'
# NeoBundle 'einars/js-beautify'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
[[plugins]]
repo = 'scrooloose/nerdcommenter'
[[plugins]]
repo = 'scrooloose/syntastic'
[[plugins]]
repo = 'Valloric/YouCompleteMe'
[[plugins]]
repo = 'SirVer/ultisnips'
[[plugins]]
repo = 'honza/vim-snippets'
[[plugins]]
repo = 'tpope/vim-surround'
[[plugins]]
repo = 'kana/vim-textobj-line'
[[plugins]]
repo = 'kana/vim-textobj-user'
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'Shougo/unite.vim'
[[plugins]]
repo = 't9md/vim-quickhl'
[[plugins]]
repo = 'rhysd/clever-f.vim'
[[plugins]]
repo = 'vimtaku/hl_matchit.vim'
[[plugins]]
repo = 'kana/vim-smartword'
[[plugins]]
repo = 'bling/vim-airline'
[[plugins]]
repo = 'lilydjwg/colorizer'
[[plugins]]
repo = 'tpope/vim-abolish'
[[plugins]]
repo = 'LeafCage/yankround.vim'
[[plugins]]
repo = 'kana/vim-textobj-jabraces'
[[plugins]]
repo = 'thinca/vim-textobj-comment'
[[plugins]]
repo = 'saihoooooooo/vim-textobj-space'
[[plugins]]
repo = 'haya14busa/vim-asterisk'
[[plugins]]
repo = 'violetyk/scratch-utility'
[[plugins]]
repo = 'airblade/vim-gitgutter'
[[plugins]]
repo = 'kana/vim-textobj-function'
[[plugins]]
repo = 'MattesGroeger/vim-bookmarks'
[[plugins]]
repo = 'Valloric/ListToggle'
[[plugins]]
repo = 'vim-scripts/csv.vim'
[[plugins]]
repo = 'mkiken/vim-bufonly'
[[plugins]]
repo = 'simeji/winresizer'
[[plugins]]
repo = 'AndrewRadev/splitjoin.vim'
[[plugins]]
repo = 'tsukkee/unite-help'
[[plugins]]
repo = 'vim-scripts/diffchar.vim'
[[plugins]]
repo      = 'tyru/open-browser.vim'

[[plugins]]
repo      = 'ujihisa/unite-colorscheme'
depends = ['unite.vim']

[[plugins]]
repo    = 'Shougo/neoyank.vim'
depends = ['unite.vim']

[[plugins]]
repo      = 'Shougo/neomru.vim'

[[plugins]]
repo      = 'Shougo/unite-outline'
depends = ['unite.vim']

[[plugins]]
repo      = 'nixprime/cpsm'
# build = 'env PY3=ON ./install.sh'
depends = ['ctrlp.vim']

# git clone 後、実行すべきコマンドがある場合はこんな感じ
[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''
