#!/bin/bash

while read local_ref local_sha1 remote_ref remote_sha1
do
  for branch in "master" "develop" "main"; do
    if [[ "${remote_ref##refs/heads/}" = "${branch}" ]]; then
      echo "Warning: push to remote ${branch}, continue? [y/N]"

      exec < /dev/tty
      read ANSWER

      case $ANSWER in
        "Y" | "y" | "yes" | "Yes" | "YES" ) echo "OK. push start.";;
        * ) echo "push failed.";exit 1;;
      esac
      exit 0
    fi
  done

  # 別名ブランチにpushしないようにする
  branch_name=$(git rev-parse --symbolic --abbrev-ref $local_ref)
  remote_branch=$(echo $remote_ref | sed 's/refs\/heads\///')

  if [ "$branch_name" != "$remote_branch" ]; then
    echo "ERROR: You are trying to push branch '$branch_name' to remote branch '$remote_branch'."
    echo "Please verify the target branch before pushing."
    exit 1
  fi

done