#!/bin/sh

# Repo="${HOME}/Desktop/repository/SettingFiles/"
Repo="`pwd`/"


echo "ln -si ${Repo}.aliases ~/.aliases"
ln -si "${Repo}.aliases" ~/.aliases

echo "ln -si ${Repo}gitfiles/.gitconfig ~/.gitconfig"
ln -si "${Repo}gitfiles/.gitconfig" ~/.gitconfig

echo "ln -si ${Repo}gitfiles/.gitignore_global ~/.gitignore"
ln -si "${Repo}gitfiles/.gitignore_global" ~/.gitignore

echo "ln -si ${Repo}vimfiles/.gvimrc ~/.gvimrc"
ln -si "${Repo}vimfiles/.gvimrc" ~/.gvimrc

echo "ln -si ${Repo}vimfiles/.vimrc ~/.vimrc"
ln -si "${Repo}vimfiles/.vimrc" ~/.vimrc

echo "ln -si ${Repo}.zshrc ~/.zshrc"
ln -si "${Repo}.zshrc" ~/.zshrc

echo "ln -si ${Repo}.emacs.d ~/.emacs.d"
ln -si "${Repo}.emacs.d" ~/.emacs.d

echo "ln -si ${Repo}vimfiles/.vim ~/.vim"
ln -si "${Repo}vimfiles/.vim" ~/.vim

echo "ln -si ${Repo}SublimeTextFiles/2/user_OSX.sublime-keymap"
ln -si "${Repo}SublimeTextFiles/2/user_OSX.sublime-keymap" ~/Library/Application\ Support/Sublime\ Text\ 2/Packages/User/Default\ \(OSX\).sublime-keymap

echo "ln -si ${Repo}SublimeTextFiles/2/default_OSX.sublime-keymap"
ln -si "${Repo}SublimeTextFiles/2/default_OSX.sublime-keymap" ~/Library/Application\ Support/Sublime\ Text\ 2/Packages/Default/Default\ \(OSX\).sublime-keymap

echo "ln -si ${Repo}SublimeTextFiles/2/Preferences.sublime-settings"
ln -si "${Repo}SublimeTextFiles/2/Preferences.sublime-settings" ~/Library/Application\ Support/Sublime\ Text\ 2/Packages/User/Preferences.sublime-settings

echo "ln -si ${Repo}.jshintrc"
ln -si "${Repo}.jshintrc" ~/.jshintrc

echo 'symbolic links created.'


# mkdir -p ~/.backup
mkdir -p ~/.backup/emacs/backup
mkdir -p ~/.backup/emacs/autosave
mkdir -p ~/.backup/vim/backup
mkdir -p ~/.backup/vim/swap

echo 'backup directory for emacs and vim made.'


# install commands

ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
brew install git
brew install rmtrash
brew install node
# brew install tree
# brew install --cocoa --srgb --with-gnutls --japanese emacs -v
brew install --cocoa --srgb --japanese emacs -v

git submodule sync
# http://rochefort.hatenablog.com/entry/20110410/p1
# git submodule foreach 'git pull origin master'
git submodule update --init --recursive
echo 'submodule update.'
