# theme
[[plugins]]
repo      = 'mhartington/oceanic-next'

[[plugins]]
repo      = 'freeo/vim-kalisi'

[[plugins]]
repo      = 'Shougo/denite.nvim'

[[plugins]]
repo      = 'Shougo/neomru.vim'

[[plugins]]
repo      = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'neomake/neomake'
hook_add = '''
autocmd! BufWritePost * Neomake
'''

[[plugins]]
repo      = 'cohama/lexima.vim'

[[plugins]]
repo      = 'flazz/vim-colorschemes'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'rickhowe/diffchar.vim'

[[plugins]]
repo = 'AndrewRadev/linediff.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'osyo-manga/vim-anzu'

[[plugins]]
repo = 'vim-airline/vim-airline'
