# theme
[[plugins]]
repo      = 'mhartington/oceanic-next'

[[plugins]]
repo      = 'freeo/vim-kalisi'

[[plugins]]
repo      = 'Shougo/denite.nvim'

[[plugins]]
repo      = 'Shougo/neomru.vim'

[[plugins]]
repo      = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'neomake/neomake'
hook_add = '''
autocmd! BufWritePost * Neomake
'''

[[plugins]]
repo      = 'cohama/lexima.vim'

[[plugins]]
repo      = 'flazz/vim-colorschemes'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'rickhowe/diffchar.vim'

[[plugins]]
repo = 'AndrewRadev/linediff.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'osyo-manga/vim-anzu'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'LeafCage/yankround.vim'

[[plugins]]
repo = 'tpope/vim-abolish'

[[plugins]]
repo = 'bronson/vim-visual-star-search'

[[plugins]]
repo = 'rhysd/committia.vim'
hook_source = '''
function! g:committia_hooks.edit_open(info)
    " Additional settings
    setlocal spell
    setlocal spelllang+=cjk

    " If no commit message, start with insert mode
    if a:info.vcs ==# 'git' && getline(1) ==# ''
        startinsert
    end

    " Scroll the diff window from insert mode
    " Map <C-n> and <C-p>
    imap <buffer><C-n> <Plug>(committia-scroll-diff-down-half)
    imap <buffer><C-p> <Plug>(committia-scroll-diff-up-half)
endfunction
'''
