[[plugins]]
repo = 'neomake/neomake'
hook_add = '''
autocmd! BufWritePost * Neomake

let g:neomake_open_list = 2
let g:neomake_cpp_enabled_makers = ['clang']
let g:neomake_cpp_clang_maker = {
    \ 'args': ['-std=c++14']
    \ }
'''

[[plugins]]
repo      = 'cohama/lexima.vim'

[[plugins]]
repo      = 'rafi/awesome-vim-colorschemes'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'rickhowe/diffchar.vim'
hook_add = '''
" vimdiff設定
" let g:DiffUnit = 'Word3' " \< or \> character class boundaries
let g:DiffUnit = 'Char' " any single character
let g:DiffColors = 3 " 16 colors in fixed order

" let g:DiffModeSync = 0
if &diff
  augroup enable_diffchar
    " diffが見やすいカラースキームを指定しておく
    " colorscheme molokai
    autocmd!
    autocmd VimEnter * execute "echom 'To word-diff be enabled, press <F7>.'"
    " neovimだと効かないのでコメントアウト(  ；∀；)
    " autocmd VimEnter * execute "%TDChar"
  augroup END
endif
'''

[[plugins]]
repo = 'AndrewRadev/linediff.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = '''
nmap n nzz<Plug>(anzu-update-search-status)<Plug>(anzu-echo-search-status)
nmap N Nzz<Plug>(anzu-update-search-status)<Plug>(anzu-echo-search-status)
nmap * *zz<Plug>(anzu-update-search-status)<Plug>(anzu-echo-search-status)
nmap # #zz<Plug>(anzu-update-search-status)<Plug>(anzu-echo-search-status)
" clear status
nmap <Esc><Esc> :nohl<CR> <Plug>(anzu-clear-search-status)
augroup vim-anzu
" 一定時間キー入力がないとき、ウインドウを移動したとき、タブを移動したときに
" 検索ヒット数の表示を消去する
    autocmd!
    autocmd CursorHold,CursorHoldI,WinLeave,TabLeave * call anzu#clear_search_status()
augroup END
'''

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'LeafCage/yankround.vim'
hook_add = '''
" vimRだとpをマッピングするとMacのクリップボードと連携できないっぽい
if !has("gui_vimr")
  " yankround
  nmap p <Plug>(yankround-p)
  xmap p <Plug>(yankround-p)
  " nmap P <Plug>(yankround-P)
  nmap gp <Plug>(yankround-gp)
  xmap gp <Plug>(yankround-gp)
  nmap gP <Plug>(yankround-gP)
  " M-p
  nmap π <Plug>(yankround-prev)
  " M-n
  nmap ˜ <Plug>(yankround-next)
endif
'''

[[plugins]]
repo = 'tpope/vim-abolish'

[[plugins]]
repo = 'bronson/vim-visual-star-search'

[[plugins]]
repo = 'rhysd/committia.vim'
hook_add = '''
" If the value is 'always', committia.vim always employs single column mode.
let g:committia_use_singlecolumn = 'always'
'''

[[plugins]]
repo = 'RRethy/vim-illuminate'

[[plugins]]
repo      = 'luochen1990/rainbow'
hook_add = '''
let g:rainbow_active = 1
'''

[[plugins]]
repo = 'yuttie/comfortable-motion.vim'

[[plugins]]
repo = 'machakann/vim-highlightedyank'

[[plugins]]
repo = 'vim-scripts/argtextobj.vim'
