#!/bin/zsh

function make_symlink () {
  echo "ln -si $1 $2"
  ln -si "$1" "$2"
}

# set Repo "$HOME/Desktop/repository/SettingFiles/"
Repo="`pwd | sed -e \"s/.\{3\}$//\"`"
Repo_shell="${Repo}shell/"

make_symlink "${Repo}"gitfiles/.gitconfig ~/.gitconfig

make_symlink "${Repo}"gitfiles/.gitignore_global ~/.gitignore

make_symlink "${Repo}"gitfiles/.git_template ~

mkdir -p ~/.config

make_symlink "${Repo}"ranger ~/.config

mkdir -p ~/.config/karabiner
make_symlink "${Repo}"mac/karabiner.json ~/.config/karabiner

make_symlink "${Repo_shell}".zshrc ~/.zshrc

make_symlink "${Repo}"gitfiles/gitui "$HOME"/.config
make_symlink "${Repo}".tmux.conf ~/.tmux.conf

make_symlink "${Repo}".ideavimrc ~/.ideavimrc

mkdir -p ~/.claude

make_symlink "${Repo}"ai/claude/settings.json ~/.claude

# touch ~/.gitconfig.local
cp -i "${Repo}gitfiles/.gitconfig.local_mac" ~/.os.gitconfig
echo "You can write LOCAL settings for git to '~/.gitconfig.local'."

echo 'symbolic links created.'


# install commands

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"


if ! command -v brew > /dev/null 2>&1; then
  if [ -f /opt/homebrew/bin/brew ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
    echo >> "$HOME"/.zprofile
    echo '[[ -f /opt/homebrew/bin/brew ]] && eval "$(/opt/homebrew/bin/brew shellenv)"' >> "$HOME"/.zprofile
  fi
fi

brew bundle

make_symlink "${BREW_PREFIX}"/share/git-core/contrib/diff-highlight/diff-highlight /usr/local/bin

make_symlink "${Repo}"vimfiles/nvim ~/.config

# touch ~/.z
touch ~/.cd_history_file

# El Capitanにアップデートした後、gitコマンドが以下のエラーを吐いて動かなくなる問題
# http://qiita.com/Ys_Jn/items/f7ff03f7a890329c3e2a
xcode-select --install

# for Tmux Plugin Manager
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# shell setting
sudo chsh -s /usr/local/bin/zsh

# for gh
gh extension install dlvhdr/gh-dash
gh extension install gennaro-tedesco/gh-f

git submodule update --init

echo "please install Sauce Code Pro Nerd Font Complete.ttf at https://www.nerdfonts.com/font-downloads."
echo "please press ^T-I in tmux to install tmux plugins."
