#!/bin/sh

function make_symlink () {
  echo "ln -si $1 $2"
  ln -si $1 $2
}

# set Repo "$HOME/Desktop/repository/SettingFiles/"
Repo="`pwd | sed -e \"s/.\{3\}$//\"`"
Repo_shell="${Repo}shell/"

make_symlink ${Repo_shell}.aliases ~/.aliases

make_symlink ${Repo}gitfiles/.gitconfig ~/.gitconfig

make_symlink ${Repo}gitfiles/.gitignore_global ~/.gitignore

make_symlink ${Repo}gitfiles/.git_template ~

mkdir -p ~/.config

make_symlink ${Repo}ranger ~/.config

make_symlink ${Repo_shell}.zshrc ~/.zshrc

make_symlink ${Repo_shell}.p10k.zsh ~/.p10k.zsh

make_symlink ${Repo}.tigrc ~/.tigrc

make_symlink ${Repo}.jshintrc ~/.jshintrc

make_symlink ${Repo}.jsbeautifyrc ~/.jsbeautifyrc

make_symlink ${Repo}.agignore ~/.agignore

make_symlink ${Repo}.tmux.conf ~/.tmux.conf

make_symlink ${Repo}.ideavimrc ~/.ideavimrc

# touch ~/.gitconfig.local
cp -i "${Repo}gitfiles/.gitconfig.local_mac" ~/.os.gitconfig
echo "You can write LOCAL settings for git to '~/.gitconfig.local'."

echo 'symbolic links created.'

# mkdir -p ~/.backup/vim/backup
# mkdir -p ~/.backup/vim/swap
# mkdir -p ~/.backup/vim/undo

# echo 'backup directory for emacs and vim made.'
# echo 'backup directory for vim made.'


# install commands

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

brew bundle

# pip3 install pynvim
python3 -m pip install --upgrade pip
python3 -m pip install --user --upgrade pynvim

# for NvChad
git clone https://github.com/NvChad/NvChad ~/.config/nvim
nvim +'hi NormalFloat guibg=#1e222a' +PackerSync
# make_symlink ${Repo}vimfiles/nvim ~/.config
make_symlink ${Repo}vimfiles/nvchad/custom ~/.config/nvim/lua

mkdir -p ~/.atom

make_symlink ${Repo}atom/.atom/config.cson ~/.atom/config.cson

make_symlink ${Repo}atom/.atom/keymap.cson ~/.atom/keymap.cson

make_symlink ${Repo}atom/.atom/snippets.cson ~/.atom/snippets.cson

make_symlink ${Repo}atom/.atom/init.coffee ~/.atom/init.coffee

make_symlink ${Repo}atom/.atom/styles.less ~/.atom/styles.less

make_symlink ${Repo}atom/atom_merge /usr/local/bin

# touch ~/.z
touch ~/.cd_history_file

# El Capitanにアップデートした後、gitコマンドが以下のエラーを吐いて動かなくなる問題
# http://qiita.com/Ys_Jn/items/f7ff03f7a890329c3e2a
xcode-select --install

# for Tmux Plugin Manager
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# shell setting
sudo chsh -s /usr/local/bin/zsh

# echo "Please setting zsh!"

# powerline用のfontを入れる
# https://mitubaex.hatenablog.com/entry/2018/04/23/044455
git clone https://github.com/powerline/fonts.git --depth=1
# install
cd fonts
./install.sh
# clean-up a bit
cd ..
rm -rf fonts

git submodule update --init

make_symlink "${Repo}submodules/used-mem/used-mem" /usr/local/bin/used-mem

echo "make symlink to diff-highlight. 'ln -si /XXXXX/share/git-core/contrib/diff-highlight/diff-highlight  /usr/local/bin'"

echo "please install Sauce Code Pro Nerd Font Complete.ttf at https://www.nerdfonts.com/font-downloads."

echo "please press ^T-I in tmux to install tmux plugins."
