#!/bin/sh

function make_symlink () {
  echo "ln -si $1 $2"
  ln -si $1 $2
}

# set Repo "$HOME/Desktop/repository/SettingFiles/"
Repo="`pwd | sed -e \"s/.\{3\}$//\"`"
Repo_shell="${Repo}shell/"
# set Repo "$SET/"

make_symlink ${Repo_shell}.aliases ~/.aliases

make_symlink ${Repo}gitfiles/.gitconfig ~/.gitconfig

make_symlink ${Repo}gitfiles/.gitignore_global ~/.gitignore

make_symlink ${Repo}gitfiles/.git_template ~

mkdir -p ~/.config
make_symlink ${Repo}vimfiles/nvim ~/.config

# for nyaovim
# mkdir -p ~/.config/nyaovim

# make_symlink ${Repo}vimfiles/nyaovim/nyaovimrc.html ~/.config/nyaovim/nyaovimrc.html
# make_symlink ${Repo}vimfiles/nyaovim/browser-config.json ~/.config/nyaovim/browser-config.json

make_symlink ${Repo_shell}.zshrc ~/.zshrc

make_symlink ${Repo}.tigrc ~/.tigrc

make_symlink ${Repo}.jshintrc ~/.jshintrc

make_symlink ${Repo}.jsbeautifyrc ~/.jsbeautifyrc

make_symlink ${Repo}.agignore ~/.agignore

# echo "ln -si ${Repo}atom/.atom/config.cson"
# ln -si "${Repo}atom/.atom/config.cson" ~/.atom/config.cson

# echo "ln -si ${Repo}atom/.atom/keymap.cson"
# ln -si "${Repo}atom/.atom/keymap.cson" ~/.atom/keymap.cson

# echo "ln -si ${Repo}atom/.atom/snippets.cson"
# ln -si "${Repo}atom/.atom/snippets.cson" ~/.atom/snippets.cson

# echo "ln -si ${Repo}atom/.atom/init.coffee"
# ln -si "${Repo}atom/.atom/init.coffee" ~/.atom/init.coffee

# echo "ln -si ${Repo}atom/.atom/styles.less"
# ln -si "${Repo}atom/.atom/styles.less" ~/.atom/styles.less

# echo "ln -si ${Repo}atom/atom_merge"
# ln -si "${Repo}atom/atom_merge" /usr/local/bin

make_symlink ${Repo}.tmux.conf ~/.tmux.conf

make_symlink ${Repo}.ideavimrc ~/.ideavimrc

make_symlink ${Repo}vscode/settings.json ~/Library/Application\ Support/Code/User/settings.json

make_symlink ${Repo}vscode/keybindings.json ~/Library/Application\ Support/Code/User/keybindings.json

# touch ~/.gitconfig.local
cp -i "${Repo}gitfiles/.gitconfig.local_mac" ~/.gitconfig.local
echo "You can write LOCAL settings for git to '~/.gitconfig.local'."

echo 'symbolic links created.'

mkdir -p ~/.backup/vim/backup
mkdir -p ~/.backup/vim/swap
mkdir -p ~/.backup/vim/undo

# echo 'backup directory for emacs and vim made.'
echo 'backup directory for vim made.'


# install commands

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
# for permission of Homebrew
sudo chown -R $USER /usr/local/
sudo chown -R $USER /Library/Caches/Homebrew/

brew install git
brew install zsh
# brew install fish
brew install rmtrash
brew install node
# brew install tree
brew install rlwrap
# brew install z
brew install tmux
brew install reattach-to-user-namespace
# brew install ghc
# brew install peco
brew install fzf
brew install ag
# brew install ripgrep
# brew install icdiff
brew install gnu-sed
brew install source-highlight
brew install tig

brew tap laurent22/massren
brew install massren
brew install ctags

# brew install go

brew install neovim

brew tap phinze/homebrew-cask
brew install brew-cask
# brew cask install atom
brew cask install iterm2
brew cask install google-chrome
# brew cask install macvim
# brew cask install vimr
brew cask install alfred
brew cask install dropbox
brew cask install clipy
brew cask install karabiner-elements
brew cask install boostnote

sudo easy_install Pygments

brew tap sambadevi/powerlevel9k && brew install powerlevel9k

# touch ~/.z
touch ~/.cd_history_file

ln -si /usr/local/share/git-core/contrib/diff-highlight/diff-highlight  /usr/local/bin

ln -si "${Repo}submodules/used-mem/used-mem" /usr/local/bin/used-mem

# massren --config editor "mvim"
massren --config editor "nvim"

# El Capitanにアップデートした後、gitコマンドが以下のエラーを吐いて動かなくなる問題
# http://qiita.com/Ys_Jn/items/f7ff03f7a890329c3e2a
xcode-select --install

# for Tmux Plugin Manager
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# shell setting
sudo chsh -s /usr/local/bin/zsh
# chsh -s $(`which fish`) $USER

# npm install -g nyaovim

# apm stars --install

# echo "Please setting zsh!"

# powerline用のfontを入れる
# https://mitubaex.hatenablog.com/entry/2018/04/23/044455
git clone https://github.com/powerline/fonts.git --depth=1
# install
cd fonts
./install.sh
# clean-up a bit
cd ..
rm -rf fonts
