#!/bin/zsh

echo "start git submodule setting."
git submodule sync
git submodule update --recursive
git submodule foreach 'git pull origin master'
echo "end git submodule setting."

echo "start brew update."
brew update -v
brew upgrade -v
brew cleanup -s
# brew reinstall --HEAD neovim
# brew reinstall --HEAD fzf
brew cask update
echo "end brew update."

# $CD_HISTORY_FILEを軽量化
if [ -n "$CD_HISTORY_FILE" ]; then
   local contents=`cat $CD_HISTORY_FILE | sort | uniq`
   echo $contents > $CD_HISTORY_FILE
fi

# deinのアップデート
nvim -c "call dein#update()" -c qa

# apmアップデート
apm update
apm upgrade
apm stars --install
zcompile ~/.zshrc
