#!/bin/zsh
#
REPO="${HOME}/Desktop/repository/"
SET="${REPO}SettingFiles/"
SUBMODULE_DIR="${SET}submodules/"

echo "start git submodule setting."
git submodule sync
git submodule update --recursive --remote
echo "end git submodule setting."

echo "start brew update."
brew update -v
brew upgrade -v
brew cleanup -s
brew bundle
echo "end brew update."

# Lazy + tree-sitterのアップデート
nvim --headless "+Lazy! sync | TSUpdate" +qa

source ${SUBMODULE_DIR}/zsh-snap/znap.zsh  # Start Znap
znap pull

zcompile ~/.zshrc
